name: CI - PHP Laravel Assessment System

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: PHPUnit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, zip, exif, pcntl, bcmath, dom, xml, ctype, json, tokenizer, pdo, pdo_mysql
          coverage: none
          tools: composer:v2

      # Step 3: Check PHP version
      - name: Verify PHP version
        run: php --version

      # Step 4: Copy environment file
      - name: Copy .env.example to .env
        run: |
          cp .env.example .env
          echo "APP_ENV=testing" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env

      # Step 5: Install dependencies
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      # Step 6: Generate application key
      - name: Generate application key
        run: php artisan key:generate

      # Step 7: Create storage directories
      - name: Create storage directories
        run: |
          mkdir -p storage/framework/{sessions,views,cache}
          chmod -R 775 storage

      # Step 8: Run database migrations
      - name: Run database migrations
        run: php artisan migrate --force

      # Step 9: Run PHPUnit tests (FIXED SYNTAX)
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --colors=always
